---
name: Build and Push to GCP

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: pwd-project-17e8b
  REGION: asia-east1
  GAR_LOCATION: asia-east1-docker.pkg.dev/pwd-project-17e8b/images
  IMAGE_NAME: demo3

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: asia-east1-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/images/$IMAGE_NAME:${{ steps.get-tag.outputs.short_ref }}
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/images/$IMAGE_NAME:latest



#      - name: Set up Cloud SDK
#        uses: google-github-actions/setup-gcloud@v2
#
#      - name: Use gcloud CLI
#        run: gcloud info
#
#      - name: "Docker auth"
#        run: |-
#          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
#
#      - name: Build image
#        run: docker build . --tag ${{ env.GAR_LOCATION }}
#        working-directory: ''
#
#      - name: Push image
#        run: docker push ${{ env.GAR_LOCATION }}



#    env:
#      IMAGE_NAME: demo3
#      PROJECT_ID: pwd-project-17e8b
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#        cache: maven
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml
#
##    - uses: actions/checkout@v4
#
#    - uses: google-github-actions/setup-gcloud@v2
#      with:
#        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
#        project_id: ${{ env.PROJECT_ID }}
#        export_default_credentials: true
#
#    - name: Build Docker Image
#      run: docker build -t $IMAGE_NAME:latest .
#
##    - name: Automatic Tagging of Releases
##      id: increment-git-tag
##      run: bash ./scripts/git_update.sh -v major
#
#    - name: Configure Docker Client
#      run:  gcloud auth configure-docker asia-east1-docker.pkg.dev
#
#    - name: Push Docker Image to Artifact Registry
#      env:
#        GIT_TAG: v0.1.0
#      run: |-
#        docker tag $IMAGE_NAME:latest asia-east1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
#        docker tag $IMAGE_NAME:latest asia-east1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
#        docker push asia-east1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
#        docker push asia-east1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
