---
name: Build and Push to GCP

on:
  push:
    branches: [ "main" ] 

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: demo3
      PROJECT_ID: pwd-project-17e8b

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
      
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

#    - name: Automatic Tagging of Releases
#      id: increment-git-tag
#      run: bash ./scripts/git_update.sh -v major

    - name: Configure Docker Client
      run:
        gcloud auth configure-docker asia-east1-docker.pkg.dev

    - name: Push Docker Image to Artifact Registry
#      env:
#        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest asia-east1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
#        docker tag $IMAGE_NAME:latest asia-east1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker push asia-east1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
#        docker push asia-east1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
