---
name: Build and Push to GCP

on:
  push:
    branches: [ "main" ] 

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: demo3
      PROJECT_ID: pwd-project-17e8b

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
      
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: run Docker Image
      run: docker run -p 8080:8080 $IMAGE_NAME:latest
    
